#eureka.client.register-with-eureka：表示是否将自身注册到 Eureka Server，默认为 true
#eureka.client.fetch-registry：表示是否从 Eureka Server 获取注册信息，默认为 true，
#                              一般单点的 Eureka Server 会将其配置为 false，集群的 Eureka Server
#                              需要同步其他 Eureka Server 的注册信息，一般选择配置为 true 或者默认值
#eureka.client.service-url.default-zone：设置与 Eureka Server 交互的地址，查询与注册服务都依赖与此地址，多个地址可以用 , 分割




server:
  port: 8058



spring:
  application:
    name: eureka-Service

#security:
#  basic:
#    enabled: true
#  user:
#    name: jeff
#    password: jeff

#eureka:
#  client:
#    register-with-eureka: false #表示是否将自身注册到 Eureka Server，默认为 true
#    fetch-registry: false #表示是否从 Eureka Server 获取注册信息
#    service-url:
#      default-zone: http://127.0.0.1:8058/eureka/ #设置与 Eureka Server 交互的地址，查询与注册服务都依赖与此地址

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://59.127.26.181:8058/eureka/
  instance:
      perferIpAddress: true